export const LOCAL_STORAGE_SEQUENCE_KEY = 'sequence'
export const LOCAL_STORAGE_TITLE_KEY = 'title'
export const LOCAL_STORAGE_TIME_SETTINGS = 'timeSettings'
export const LOCAL_STORAGE_EDITING_BLOCK = 'editingBlock'
export const LOCAL_STORAGE_THEME_PREFERENCE = 'themePreference'
